num_enc: 8 # 8
num_dec: 8 # 8
num_heads: 6 # 4
soundfont: "./GeneralUser_GS_v1.471.sf2"
batch_size: 2 # 128 HOW MANY SONGS TO LOAD
ffn_hidden: 1024 # 1024
emb_dim: 512
vocab_size: 631
learningrate: .001
num_epochs: 1
midi_dir: './lmd_tracks'
audio_dir:  '/raw_audio'
