num_enc: 2 # 8
num_dec: 2 # 8
num_heads: 2 # 4
batch_size: 2 # 128 HOW MANY SONGS TO LOAD
ffn_hidden: 128 # 1024
emb_dim: 512
learningrate: .0001
num_epochs: 2
train_paths: '../data_lists/trainfiles_sma.p'
eval_paths: '../data_lists/testfiles_sma.p'